// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Styles$Googleplacesautocomplete = require("./Styles.bs.js");

var component = ReasonReact.statelessComponent("Address");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("table", {
                          id: "address"
                        }, React.createElement("tbody", undefined, React.createElement("tr", undefined, React.createElement("td", {
                                      className: Styles$Googleplacesautocomplete.label
                                    }, "Street address"), React.createElement("td", {
                                      className: Styles$Googleplacesautocomplete.slimField
                                    }, React.createElement("input", {
                                          className: Styles$Googleplacesautocomplete.field,
                                          id: "street_number",
                                          disabled: true
                                        })), React.createElement("td", {
                                      className: Styles$Googleplacesautocomplete.wideField,
                                      colSpan: 2
                                    }, React.createElement("input", {
                                          className: Styles$Googleplacesautocomplete.field,
                                          id: "route",
                                          disabled: true
                                        }))), React.createElement("tr", undefined, React.createElement("td", {
                                      className: Styles$Googleplacesautocomplete.label
                                    }, "City"), React.createElement("td", {
                                      className: Styles$Googleplacesautocomplete.wideField,
                                      colSpan: 3
                                    }, React.createElement("input", {
                                          className: Styles$Googleplacesautocomplete.field,
                                          id: "locality",
                                          disabled: true
                                        }))), React.createElement("tr", undefined, React.createElement("td", {
                                      className: Styles$Googleplacesautocomplete.label
                                    }, "State"), React.createElement("td", {
                                      className: Styles$Googleplacesautocomplete.slimField
                                    }, React.createElement("input", {
                                          className: Styles$Googleplacesautocomplete.field,
                                          id: "administrative_area_level_1",
                                          disabled: true
                                        })), React.createElement("td", {
                                      className: Styles$Googleplacesautocomplete.label
                                    }, "Zip code"), React.createElement("td", {
                                      className: Styles$Googleplacesautocomplete.wideField
                                    }, React.createElement("input", {
                                          className: Styles$Googleplacesautocomplete.field,
                                          id: "postal_code",
                                          disabled: true
                                        }))), React.createElement("tr", undefined, React.createElement("td", {
                                      className: Styles$Googleplacesautocomplete.label
                                    }, "Country"), React.createElement("td", {
                                      className: Styles$Googleplacesautocomplete.wideField,
                                      colSpan: 3
                                    }, React.createElement("input", {
                                          className: Styles$Googleplacesautocomplete.field,
                                          id: "country",
                                          disabled: true
                                        })))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
