// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var types = {
  types: /* array */["geocode"]
};

function marshall(components, len) {
  var switcher = len - 1 | 0;
  if (switcher > 8 || switcher < 0) {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "Googleplaces.re",
            60,
            11
          ]
        ];
  } else {
    switch (switcher) {
      case 0 : 
          return {
                  street_number: "",
                  route: "",
                  locality: "",
                  administrative_area_level_1: "",
                  country: Caml_array.caml_array_get(components, 0).long_name,
                  postal_code: ""
                };
      case 1 : 
          return {
                  street_number: "",
                  route: "",
                  locality: "",
                  administrative_area_level_1: Caml_array.caml_array_get(components, 0).short_name,
                  country: Caml_array.caml_array_get(components, 1).long_name,
                  postal_code: ""
                };
      case 2 : 
          throw [
                Caml_builtin_exceptions.match_failure,
                /* tuple */[
                  "Googleplaces.re",
                  60,
                  11
                ]
              ];
      case 3 : 
          return {
                  street_number: "",
                  route: "",
                  locality: Caml_array.caml_array_get(components, 0).long_name,
                  administrative_area_level_1: Caml_array.caml_array_get(components, 2).short_name,
                  country: Caml_array.caml_array_get(components, 3).long_name,
                  postal_code: ""
                };
      case 4 : 
          return {
                  street_number: "",
                  route: Caml_array.caml_array_get(components, 0).long_name,
                  locality: "",
                  administrative_area_level_1: Caml_array.caml_array_get(components, 2).short_name,
                  country: Caml_array.caml_array_get(components, 3).long_name,
                  postal_code: Caml_array.caml_array_get(components, 4).short_name
                };
      case 5 : 
          return {
                  street_number: "",
                  route: "",
                  locality: Caml_array.caml_array_get(components, 1).long_name,
                  administrative_area_level_1: Caml_array.caml_array_get(components, 3).short_name,
                  country: Caml_array.caml_array_get(components, 4).long_name,
                  postal_code: Caml_array.caml_array_get(components, 5).short_name
                };
      case 6 : 
          return {
                  street_number: Caml_array.caml_array_get(components, 0).long_name,
                  route: Caml_array.caml_array_get(components, 1).long_name,
                  locality: Caml_array.caml_array_get(components, 2).long_name,
                  administrative_area_level_1: Caml_array.caml_array_get(components, 4).short_name,
                  country: Caml_array.caml_array_get(components, 5).long_name,
                  postal_code: Caml_array.caml_array_get(components, 6).short_name
                };
      case 7 : 
          return {
                  street_number: Caml_array.caml_array_get(components, 0).long_name,
                  route: Caml_array.caml_array_get(components, 1).long_name,
                  locality: Caml_array.caml_array_get(components, 4).long_name,
                  administrative_area_level_1: Caml_array.caml_array_get(components, 5).short_name,
                  country: Caml_array.caml_array_get(components, 6).long_name,
                  postal_code: Caml_array.caml_array_get(components, 7).short_name
                };
      case 8 : 
          return {
                  street_number: Caml_array.caml_array_get(components, 0).long_name,
                  route: Caml_array.caml_array_get(components, 1).long_name,
                  locality: Caml_array.caml_array_get(components, 3).long_name,
                  administrative_area_level_1: Caml_array.caml_array_get(components, 5).short_name,
                  country: Caml_array.caml_array_get(components, 6).long_name,
                  postal_code: Caml_array.caml_array_get(components, 7).short_name + ("-" + Caml_array.caml_array_get(components, 8).short_name)
                };
      
    }
  }
}

exports.types = types;
exports.marshall = marshall;
/* No side effect */
