// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Form$Googleplacesautocomplete = require("./Form.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Form$Googleplacesautocomplete.make(/* array */[])), "index");

/*  Not a pure module */
