// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

var label = Css.style(/* :: */[
      Css.fontWeight(400),
      /* :: */[
        Css.textAlign(/* right */-379319332),
        /* :: */[
          Css.width(/* `px */[
                25096,
                100
              ]),
          /* :: */[
            Css.color(Css.grey),
            /* [] */0
          ]
        ]
      ]
    ]);

var field = Css.style(/* :: */[
      Css.width(/* `percent */[
            -119887163,
            99
          ]),
      /* [] */0
    ]);

var slimField = Css.style(/* :: */[
      Css.width(/* `px */[
            25096,
            80
          ]),
      /* [] */0
    ]);

var wideField = Css.style(/* :: */[
      Css.width(/* `px */[
            25096,
            200
          ]),
      /* [] */0
    ]);

exports.label = label;
exports.field = field;
exports.slimField = slimField;
exports.wideField = wideField;
/* label Not a pure module */
